In [290]:
import numpy as np
import pandas as pd
from scipy import stats

In [235]:
data = pd.read_csv("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\ARS\\housing_data.csv")
data

No  Square  Bedrooms  Age  Floors  Price
0    1      40         2   12       3   1480
1    2      42         2    5       3   1560
2    3      45         3    6       3   1600
3    4      48         4    8       4   1640
4    5      50         6   11       4   1718
5    6      53         3    9       3   1830
6    7      55         4    7       4   1700
7    8      60         4    2       3   1970
8    9      63         3    3       3   1870
9   10      65         3    4       2   1987
10  11      67         4    6       4   1930
11  12      69         6    7       5   1967
12  13      72         6    9       6   2150
13  14      74         3    3       2   2120
14  15      75         3    4       3   2050
15  16      78         3    2       4   2080
16  17      82         5    5       4   2140
17  18      85         5   10       4   2100
18  19      90         6    2       6   2400
19  20      92         5    7       5   2370
20  21      94         6   15       7   2205
21  22      97         6    1       4   2650
22  23     101         5   12       4   2800
23  24     109         8   10       6   3100

In [236]:
arr = np.array(data)
arr

array([[   1,   40,    2,   12,    3, 1480],
       [   2,   42,    2,    5,    3, 1560],
       [   3,   45,    3,    6,    3, 1600],
       [   4,   48,    4,    8,    4, 1640],
       [   5,   50,    6,   11,    4, 1718],
       [   6,   53,    3,    9,    3, 1830],
       [   7,   55,    4,    7,    4, 1700],
       [   8,   60,    4,    2,    3, 1970],
       [   9,   63,    3,    3,    3, 1870],
       [  10,   65,    3,    4,    2, 1987],
       [  11,   67,    4,    6,    4, 1930],
       [  12,   69,    6,    7,    5, 1967],
       [  13,   72,    6,    9,    6, 2150],
       [  14,   74,    3,    3,    2, 2120],
       [  15,   75,    3,    4,    3, 2050],
       [  16,   78,    3,    2,    4, 2080],
       [  17,   82,    5,    5,    4, 2140],
       [  18,   85,    5,   10,    4, 2100],
       [  19,   90,    6,    2,    6, 2400],
       [  20,   92,    5,    7,    5, 2370],
       [  21,   94,    6,   15,    7, 2205],
       [  22,   97,    6,    1,    4, 2650],
       [  

In [237]:
X = arr[:,1:5]
X

array([[ 40,   2,  12,   3],
       [ 42,   2,   5,   3],
       [ 45,   3,   6,   3],
       [ 48,   4,   8,   4],
       [ 50,   6,  11,   4],
       [ 53,   3,   9,   3],
       [ 55,   4,   7,   4],
       [ 60,   4,   2,   3],
       [ 63,   3,   3,   3],
       [ 65,   3,   4,   2],
       [ 67,   4,   6,   4],
       [ 69,   6,   7,   5],
       [ 72,   6,   9,   6],
       [ 74,   3,   3,   2],
       [ 75,   3,   4,   3],
       [ 78,   3,   2,   4],
       [ 82,   5,   5,   4],
       [ 85,   5,  10,   4],
       [ 90,   6,   2,   6],
       [ 92,   5,   7,   5],
       [ 94,   6,  15,   7],
       [ 97,   6,   1,   4],
       [101,   5,  12,   4],
       [109,   8,  10,   6]], dtype=int64)

In [238]:
Y = arr[:,5:6]
Y

array([[1480],
       [1560],
       [1600],
       [1640],
       [1718],
       [1830],
       [1700],
       [1970],
       [1870],
       [1987],
       [1930],
       [1967],
       [2150],
       [2120],
       [2050],
       [2080],
       [2140],
       [2100],
       [2400],
       [2370],
       [2205],
       [2650],
       [2800],
       [3100]], dtype=int64)

In [239]:
#chuan hoa
X = stats.zscore(X, axis=0)
X

array([[-1.60408224, -1.56003457,  1.44857194, -0.79471941],
       [-1.50087052, -1.56003457, -0.45267873, -0.79471941],
       [-1.34605293, -0.90317791, -0.18107149, -0.79471941],
       [-1.19123534, -0.24632125,  0.36214298,  0.        ],
       [-1.08802361,  1.06739208,  1.1769647 ,  0.        ],
       [-0.93320602, -0.90317791,  0.63375022, -0.79471941],
       [-0.8299943 , -0.24632125,  0.09053575,  0.        ],
       [-0.57196498, -0.24632125, -1.26750044, -0.79471941],
       [-0.41714739, -0.90317791, -0.99589321, -0.79471941],
       [-0.31393567, -0.90317791, -0.72428597, -1.58943883],
       [-0.21072394, -0.24632125, -0.18107149,  0.        ],
       [-0.10751221,  1.06739208,  0.09053575,  0.79471941],
       [ 0.04730537,  1.06739208,  0.63375022,  1.58943883],
       [ 0.1505171 , -0.90317791, -0.99589321, -1.58943883],
       [ 0.20212296, -0.90317791, -0.72428597, -0.79471941],
       [ 0.35694055, -0.90317791, -1.26750044,  0.        ],
       [ 0.563364  ,  0.

In [240]:
muy_Y = np.mean(Y, axis =0)
muy_Y = np.ndarray.item(muy_Y)
muy_Y

2059.0416666666665

In [241]:
sigma_Y = np.std(Y, axis =0)
sigma_Y = np.ndarray.item(sigma_Y)
sigma_Y

386.1748825733693

In [242]:
Y = stats.zscore(Y, axis =0)
Y

array([[-1.49942861],
       [-1.29226858],
       [-1.18868856],
       [-1.08510855],
       [-0.88312752],
       [-0.59310348],
       [-0.92973853],
       [-0.23057343],
       [-0.48952347],
       [-0.18655192],
       [-0.33415344],
       [-0.23834193],
       [ 0.23553664],
       [ 0.15785163],
       [-0.0234134 ],
       [ 0.05427161],
       [ 0.20964163],
       [ 0.10606162],
       [ 0.88291173],
       [ 0.80522672],
       [ 0.37795916],
       [ 1.53028682],
       [ 1.91871188],
       [ 2.69556199]])

In [243]:
#tach
X_train = X[0:20,:]
X

array([[-1.60408224, -1.56003457,  1.44857194, -0.79471941],
       [-1.50087052, -1.56003457, -0.45267873, -0.79471941],
       [-1.34605293, -0.90317791, -0.18107149, -0.79471941],
       [-1.19123534, -0.24632125,  0.36214298,  0.        ],
       [-1.08802361,  1.06739208,  1.1769647 ,  0.        ],
       [-0.93320602, -0.90317791,  0.63375022, -0.79471941],
       [-0.8299943 , -0.24632125,  0.09053575,  0.        ],
       [-0.57196498, -0.24632125, -1.26750044, -0.79471941],
       [-0.41714739, -0.90317791, -0.99589321, -0.79471941],
       [-0.31393567, -0.90317791, -0.72428597, -1.58943883],
       [-0.21072394, -0.24632125, -0.18107149,  0.        ],
       [-0.10751221,  1.06739208,  0.09053575,  0.79471941],
       [ 0.04730537,  1.06739208,  0.63375022,  1.58943883],
       [ 0.1505171 , -0.90317791, -0.99589321, -1.58943883],
       [ 0.20212296, -0.90317791, -0.72428597, -0.79471941],
       [ 0.35694055, -0.90317791, -1.26750044,  0.        ],
       [ 0.563364  ,  0.

In [244]:
X_test = X[20:24,:]
X_test

array([[ 1.18263436,  1.06739208,  2.26339365,  2.38415824],
       [ 1.33745195,  1.06739208, -1.53910768,  0.        ],
       [ 1.5438754 ,  0.41053541,  1.44857194,  0.        ],
       [ 1.95672231,  2.3811054 ,  0.90535746,  1.58943883]])

In [245]:
Y_train = Y[0:20,:]
Y_train

array([[-1.49942861],
       [-1.29226858],
       [-1.18868856],
       [-1.08510855],
       [-0.88312752],
       [-0.59310348],
       [-0.92973853],
       [-0.23057343],
       [-0.48952347],
       [-0.18655192],
       [-0.33415344],
       [-0.23834193],
       [ 0.23553664],
       [ 0.15785163],
       [-0.0234134 ],
       [ 0.05427161],
       [ 0.20964163],
       [ 0.10606162],
       [ 0.88291173],
       [ 0.80522672]])

In [246]:
Y_test = Y[20:24,:]
Y_test

array([[0.37795916],
       [1.53028682],
       [1.91871188],
       [2.69556199]])

In [247]:
#trien khai mo hinh
def calculate_y_hat(W,X,b):
    n = W.shape[0]
    m = X.shape[0]
    Y_HAT = np.zeros(m)
    for i in range(m):
        Y_HAT[i] = np.dot(W, X[i])+b
    return Y_HAT

In [274]:
def calculate_cost(y_hat,y):
    m = y_hat.shape[0]
    cost = 0
    for i in range(m):
        cost += (y_hat[i] - y[i]) ** 2

    cost /= 2 * m
    return cost

In [276]:
def calculate_derivative(W,b,X,Y):
    n = W.shape[0] #so feature
    dW = np.zeros(n)
    db = 0
    m = X.shape[0] #so phan tu

    for j in range(n):
        for i in range(m):
            dW[j] += (np.dot(W, X[i]) + b - Y[i]) * X[i][j]
        dW[j] /= m

    for i in range(m):
        db += (np.dot(W, X[i]) + b - Y[i])
    db /= m
    return dW, db

In [366]:
W = np.random.rand(X.shape[1])*0.01
print(W)
b = np.random.rand()*0.01
print(b)

[0.00067868 0.00815754 0.00889958 0.00471684]
0.001499742112832363


In [401]:
learning_rate = 0.01
n_iters = 200

for k in range(n_iters):
    dW, db = calculate_derivative(W,b,X,Y)

    W = W - learning_rate * dW
    b = b - learning_rate * db
    Y_HAT = calculate_y_hat(W, X, b)

    # Tính cost
    cost = calculate_cost(Y_HAT, Y)

    # In ra cost sau mỗi 10 bước lặp
    if (k + 1) % 10 == 0:
        print("Cost:", cost)

Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]
Cost: [0.03899863]


C:\Users\Admin\AppData\Local\Temp\ipykernel_16208\3222116444.py:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dW[j] += (np.dot(W, X[i]) + b - Y[i]) * X[i][j]
C:\Users\Admin\AppData\Local\Temp\ipykernel_16208\1311969126.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Y_HAT[i] = np.dot(W, X[i])+b


In [409]:
Y_HAT_Test = calculate_y_hat(W, X_test, b)
Y_HAT_Test

C:\Users\Admin\AppData\Local\Temp\ipykernel_16208\1311969126.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Y_HAT[i] = np.dot(W, X[i])+b


array([0.77742865, 1.49213003, 1.49044926, 2.03516093])

In [308]:
Y_test

array([[0.37795916],
       [1.53028682],
       [1.91871188],
       [2.69556199]])

In [411]:
Y_HAT_Test = Y_HAT_Test * sigma_Y + muy_Y
Y_HAT_Test

array([2359.26508314, 2635.26480528, 2634.61573533, 2844.96970094])

In [272]:
Y_Test = Y_test * sigma_Y + muy_Y
Y_Test.T

array([[2205., 2650., 2800., 3100.]])